ARG VARIANT=3
FROM mcr.microsoft.com/devcontainers/python:3.13-bullseye

ENV FLASK_APP=run:app
ENV FLASK_DEBUG=1

COPY requirements.txt /tmp/pip-tmp/

# nainstalujeme jq před pipem, pak smažeme cache apt a doinstalujeme Python závislosti
RUN apt-get update \
 && apt-get install -y jq \
 && pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
 && rm -rf /tmp/pip-tmp /var/lib/apt/lists/*

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
